version: '3.8'

services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build:
      context: app/
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis

  # fastapi:
  #   build:
  #     context: fastapi/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: bitnami/redis:7.0.15
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
