services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - .env
    depends_on:
      - django
    volumes:
      - .ssl/chess-auto-chess.crt:/etc/ssl/cert.crt
      - .ssl/chess-auto-chess.key:/etc/ssl/cert.key

  django:
    build:
      context: app/
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
      - redis

  migrate:
    build:
      context: app/
      dockerfile: Dockerfile
    env_file: 
      - .env
    command: python ./manage.py migrate
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    env_file: 
      - .env
    volumes:
      - chess_postgres_data:/var/lib/postgresql/data
    # profiles: 
    #   - storage

  redis:
    image: bitnami/redis:7.0.15
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # profiles: 
    #   - storage

volumes:
  chess_postgres_data:
    external: true