version: '3.8'

services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django

  django:
    build:
      context: app/
      dockerfile: Dockerfile
    depends_on:
      - migrate

  migrate:
    build:
      context: app/
      dockerfile: Dockerfile
    environment:
      DJANGO_SUPERUSER_PASSWORD: root
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: root@mail.ru
    command: python ./manage.py makemigrations && python ./manage.py migrate
    depends_on:
      - postgres
  
  create_superuser:
    build:
      context: app/
      dockerfile: Dockerfile
    environment:
      DJANGO_SUPERUSER_PASSWORD: root
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: root@mail.ru
    command: python ./manage.py createsuperuser --noinput | true
    depends_on:
      - migrate
      - postgres

  # fastapi:
  #   build:
  #     context: fastapi/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.0.15
    # ports:
    #   - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
