services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - .env
    depends_on:
      - django

  django:
    build:
      context: app/
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
      - redis

  migrate:
    build:
      context: app/
      dockerfile: Dockerfile
    command: python ./manage.py migrate
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:7.0.15
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
