name: Docker Build and Push

on:
  push:
    tags:
      - '*'  # сборка производится только при наличии тега
    branches:
      - main  # измените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin your-registry.example.com

    - name: Build Docker image
      run: docker build -t your-registry.example.com/your-image-name:${{ github.ref }} .

    - name: Push Docker image
      run: docker push your-registry.example.com/your-image-name:${{ github.ref }}
